Iteration 2
CaptainPhilipp/cycle_aggregator pull request #18
Opened 2017-10-01 14:15 UTC by CaptainPhilipp

2017-10-10 18:41 UTC, vkurennov approved these changes

2017-10-10 18:41 UTC, vkurennov commented on app/services/childrens_view.rb
> +class ChildrensView
Children - это и так множественное число слова  child, нет слова childrenS

2017-10-10 18:43 UTC, vkurennov requested changes

2017-10-10 18:43 UTC, vkurennov commented on app/services/childrens_view.rb
> +class ChildrensView
И почему у тебя нет тестов на сервисные классы? кроме того, сервисные классы - это уровень бизнес-логики, т.е. уровень моделей в архитектуре MVC, а  у тебя тут некий View. Может, просто название неудачное?

2017-10-10 20:40 UTC, CaptainPhilipp commented on app/services/childrens_view.rb
> +class ChildrensView
Да, с children-childs то и дело забываю.
А по View очень долго думал чем заменить. Либо тоже коллекция (но все-таки коллекции это то что использует сия сущность), либо... Ему более родственен Фасад как мне кажется, но название это будет не говорящее. Так и не смог придумать достойное название. По сути это инструмент работы с IndexCollections, для выдачи нужных записей из оных.

под View имелся в виду ViewObject, но это тоже неверное сравнение т.к. последний не имеет отношения к представлению коллекций.

2017-10-11 07:32 UTC, CaptainPhilipp commented on app/services/childrens_view.rb
> +class ChildrensView
название неудачное, согласен. долго думал, ничего лучше не придумал. View тут больше ассоциируется с ViewObject, но это тоже очень неправильно.

а тест на этот сервис есть, просто я после череды переименований (искал имя), забыл переименовать сами спеки. Не хватало теста на IndexedCollection, который использовался другими оттестированными компонентами.

сейчас спек переименовал, недостающий дописал. Прикреплю к следующей итерации.

2017-10-11 07:55 UTC, CaptainPhilipp commented on app/services/childrens_view.rb
> +    raise ArgumentError if indexed_childrens.nil? || indexed_relations.nil?
TODO: добавить проверку `respond_to? :by_key` или `is_a? IndexedCollection`

2017-10-11 08:00 UTC, CaptainPhilipp commented on app/services/indexed_collection.rb
> +  def indexed_by_one(key)
TODO: rename to `indexed_by_one_key(key)`

2017-10-11 08:06 UTC, CaptainPhilipp commented on app/views/layouts/application/_menu.slim
> +                - show_subshow_sections_for(group, section).each do |subsection|
TODO: `show_subsections_for`
жертва автоматического переименования. вообще-то было исправлено, не знаю в какой момент отменил этот небольшой фикс.

2017-10-11 08:08 UTC, CaptainPhilipp commented on app/views/parameters/_range.slim
> +- range = values.first
TODO: файл пока не используется, удалить.

2017-10-11 08:18 UTC, CaptainPhilipp commented on spec/services/where_parents_query_spec.rb
> +    context 'with array of records' do
TODO: поменять местами названия контекстов. упс...

2017-10-11 09:07 UTC, CaptainPhilipp commented on app/helpers/application_helper.rb
> +    @sections_view ||= ChildrensView.new(@indexed_sections, @indexed_relations)
TODO: заменить в имени переменной `_view` на что-то более подходящее

2017-10-11 09:53 UTC, CaptainPhilipp commented on app/services/values_present_type.rb
> +    parameter.present_type ||= calculate_present_type
ошибка. объект не должен менять другой объект. правильно:
`parameter.present_type || calculate_present_type`

2017-10-11 09:58 UTC, CaptainPhilipp commented on app/services/values_present_type.rb
> +# functional object, calculates present_type by given data
TODO: # chose present_type by values_type and values length

2017-10-11 10:00 UTC, CaptainPhilipp commented on app/services/where_parents_query.rb
> +    if parents.is_a? Hash
TODO: switch case

2017-10-11 11:20 UTC, CaptainPhilipp commented on app/services/where_parents_query.rb
> +# AR query, that returns childs, having all (not any) of concrete parents
TODO: # Can be explaned as: `ChildsModel.where(id: parent1.child_ids & parent2.child_ids & parentN.child_ids)`

2017-10-11 11:43 UTC, CaptainPhilipp commented on app/services/indexed_collection.rb
> +  def find_by_multiple_conditions(conditions)
TODO: rename to `find_by_multiple_keys`

2017-10-11 11:43 UTC, CaptainPhilipp commented on app/services/indexed_collection.rb
> +  def find_by_one_condition(key, value)
TODO: rename to find_by_one_key

2017-10-12 06:29 UTC, merged